// packages/solid/src/components/Button/Button.tsx
import type { ColorScheme, Size, Variant } from '@kivora/core';
import { cx, getButtonClasses } from '@kivora/core';
import type { Component, JSX } from 'solid-js';
import { splitProps } from 'solid-js';

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: Variant;
	size?: Size;
	colorScheme?: ColorScheme;
	isLoading?: boolean;
	fullWidth?: boolean;
	leftIcon?: JSX.Element;
	rightIcon?: JSX.Element;
}

export const Button: Component<ButtonProps> = (rawProps) => {
	const [local, rest] = splitProps(rawProps, [
		'variant',
		'size',
		'colorScheme',
		'isLoading',
		'fullWidth',
		'leftIcon',
		'rightIcon',
		'class',
		'children',
	]);

	const classes = () =>
		cx(
			getButtonClasses({
				variant: local.variant ?? 'solid',
				size: local.size ?? 'md',
				colorScheme: local.colorScheme ?? 'primary',
				disabled: rest.disabled || local.isLoading,
			}),
			local.fullWidth ? 'kv-btn--full' : undefined,
			local.class,
		);

	return (
		<button
			class={classes()}
			disabled={rest.disabled || local.isLoading}
			{...rest}>
			{local.isLoading && (
				<span
					class='kv-spinner'
					aria-hidden='true'
				/>
			)}
			{!local.isLoading && local.leftIcon && (
				<span class='kv-btn__icon kv-btn__icon--left'>
					{local.leftIcon}
				</span>
			)}
			<span class='kv-btn__label'>{local.children}</span>
			{!local.isLoading && local.rightIcon && (
				<span class='kv-btn__icon kv-btn__icon--right'>
					{local.rightIcon}
				</span>
			)}
		</button>
	);
};

// packages/svelte/src/components/Button/Button.svelte
<script lang="ts">
  import type { ColorScheme, Size, Variant } from "../../_core";
  import { getButtonClasses, cx } from "../../_core";

  interface Props {
    variant?: Variant;
    size?: Size;
    colorScheme?: ColorScheme;
    isLoading?: boolean;
    fullWidth?: boolean;
    disabled?: boolean;
    class?: string;
    onclick?: (e: MouseEvent) => void;
    children?: import("svelte").Snippet;
  }

  let {
    variant = "solid",
    size = "md",
    colorScheme = "primary",
    isLoading = false,
    fullWidth = false,
    disabled = false,
    class: className = "",
    onclick,
    children,
  }: Props = $props();

  const classes = $derived(
    cx(
      getButtonClasses({ variant, size, colorScheme, disabled: disabled || isLoading }),
      fullWidth ? "kv-btn--full" : undefined,
      className
    )
  );
</script>

<button
  class={classes}
  disabled={disabled || isLoading}
  {onclick}
>
  {#if isLoading}
    <span class="kv-spinner" aria-hidden="true"></span>
  {:else}
    {@render children?.()}
  {/if}
</button>
